name: Generate and Publish Dokka Docs

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: "Version for manual run (e.g., 1.2.0)"
        required: true
        default: "manual"

permissions:
  contents: write

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Cache Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build Dokka HTML MultiModule
        run: |
          chmod +x ./gradlew
          ./gradlew dokkaHtmlMultiModule

      - name: Prepare versioned output
        id: prep
        shell: bash
        run: |
          if [[ "${GITHUB_EVENT_NAME}" == "release" ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
          else
            VERSION=${{ github.event.inputs.version }}
          fi

          # Remove 'v' prefix if someone adds it accidentally
          VERSION=${VERSION#v}

          echo "Using version: $VERSION"
          echo "version=$VERSION" >> $GITHUB_OUTPUT

          mkdir -p docs/versioned/$VERSION
          cp -r build/dokka/html/* docs/versioned/$VERSION/

          # Also update /latest
          rm -rf docs/latest
          mkdir -p docs/latest
          cp -r build/dokka/html/* docs/latest/

      - name: Add index redirect
        run: |
          echo '<meta http-equiv="refresh" content="0; url=latest/">' > docs/index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          publish_branch: gh-pages
          keep_files: true
